const subjects=["Biology","Chemistry","Physics","Mathematics"];
const starter=["Cell Biology","Molecular Biology","Genetics","Biochemistry","Microbiology","Plant Biology","Animal Biology","Ecology & Evolution","Atomic Structure","Periodicity","Chemical Bonding","Thermodynamics","Chemical Equilibrium","Organic Chemistry","Inorganic Chemistry","Units & Dimensions","Mechanics","Properties of Matter","Thermodynamics","Waves & Oscillations","Electrostatics","Current Electricity","Optics","Modern Physics","Sets & Functions","Algebra","Complex Numbers","Calculus","Coordinate Geometry","Probability & Statistics"];
const starterSubject=i=>i<8?"Biology":i<15?"Chemistry":i<24?"Physics":"Mathematics";
const demo=()=>({topics:starter.map((name,i)=>({id:crypto.randomUUID(),subject:starterSubject(i),name,mastery:"Not started"})),study:[],tests:[],revisions:[]});
let db={topics:[],study:[],tests:[],revisions:[]}, supabaseClient=null, user=null;
if(window.SUPABASE_URL && !window.SUPABASE_URL.startsWith("YOUR_")) supabaseClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function authInit(){if(!supabaseClient){user={id:"local",email:"Local mode"};db=JSON.parse(localStorage.getItem("jamv2")||"null")||demo();showApp();return}let {data}=await supabaseClient.auth.getSession();if(data.session){user=data.session.user;await loadCloud();showApp()}else $("auth").classList.remove("hidden");supabaseClient.auth.onAuthStateChange(async(_,s)=>{if(s){user=s.user;await loadCloud();showApp()}})}
async function loadCloud(){let uid=user.id;let [a,b,c,d]=await Promise.all([supabaseClient.from("topics").select("*").eq("user_id",uid),supabaseClient.from("study_sessions").select("*").eq("user_id",uid),supabaseClient.from("tests").select("*").eq("user_id",uid),supabaseClient.from("revisions").select("*").eq("user_id",uid)]);db={topics:a.data||[],study:(b.data||[]).map(x=>({...x,hours:Number(x.hours)})),tests:c.data||[],revisions:d.data||[]};if(!db.topics.length){db=demo();await saveCloud()}}
async function saveCloud(){if(!supabaseClient){localStorage.setItem("jamv2",JSON.stringify(db));return}let uid=user.id;for(const t of db.topics) await supabaseClient.from("topics").upsert({...t,user_id:uid});}
function showApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userEmail").textContent=user.email||"";render()}
function pct(n){return Math.round(n||0)+"%"} function stats(t){let tests=db.tests.filter(x=>x.topic_id===t.id),rev=db.revisions.filter(x=>x.topic_id===t.id),study=db.study.filter(x=>x.topic_id===t.id);return{tests,rev,hrs:study.reduce((a,x)=>a+Number(x.hours||0),0),avg:tests.length?tests.reduce((a,x)=>a+Number(x.percent||0),0)/tests.length:0}}
function render(){let strong=db.topics.filter(x=>["Strong","Exam ready"].includes(x.mastery)).length, total=db.topics.length, hours=db.study.reduce((a,x)=>a+Number(x.hours||0),0),avg=db.tests.length?db.tests.reduce((a,x)=>a+x.percent,0)/db.tests.length:0;$("overall").textContent=pct(total?strong/total*100:0);$("kpis").innerHTML=[["Mastered",`${strong}/${total}`,"topics"],["Study hours",hours.toFixed(1),"logged"],["Tests",db.tests.length,"attempts"],["Average",pct(avg),"test score"]].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join("");$("subjects").innerHTML=subjects.map(s=>{let a=db.topics.filter(x=>x.subject===s),n=a.filter(x=>["Strong","Exam ready"].includes(x.mastery)).length,p=a.length?n/a.length*100:0;return `<div class="progress"><div class="pl"><span>${s}</span><b>${pct(p)}</b></div><div class="bar"><div class="fill" style="width:${p}%"></div></div></div>`}).join("");let pri=db.topics.map(t=>({...t,q:stats(t),rank:(["Not started","Learning"].includes(t.mastery)?30:0)+(stats(t).avg<60&&stats(t).tests.length?35:0)+(stats(t).rev.length===0&&t.mastery!=="Not started"?20:0)})).sort((a,b)=>b.rank-a.rank).slice(0,5);$("priorities").innerHTML=pri.length?pri.map(t=>`<div class="priority"><span>${esc(t.subject)} · ${esc(t.name)}</span><b>${t.mastery==="Not started"?"Start":t.q.avg<60&&t.q.tests.length?"Revise + test":"Revise"}</b></div>`).join(""):"<p>No topics yet.</p>";renderTopics();renderStudy();renderTests();renderRevs();renderAnalytics()}
function renderTopics(){let sf=$("sf"),old=sf.value||"All subjects";sf.innerHTML="<option>All subjects</option>"+subjects.map(s=>`<option>${s}</option>`).join("");sf.value=old;let mf=$("mf").value;let list=db.topics.filter(t=>(old==="All subjects"||t.subject===old)&&(mf==="All mastery"||t.mastery===mf));$("topicRows").innerHTML=list.map(t=>{let q=stats(t);return `<tr><td>${esc(t.subject)}</td><td><b>${esc(t.name)}</b></td><td><select onchange="mastery('${t.id}',this.value)">${["Not started","Learning","Practiced","Strong","Exam ready"].map(x=>`<option ${x===t.mastery?"selected":""}>${x}</option>`).join("")}</select></td><td>${q.hrs.toFixed(1)}</td><td>${q.tests.length}</td><td>${q.tests.length?pct(q.avg):"—"}</td><td>${q.rev.length}</td><td><button class="del" onclick="removeTopic('${t.id}')">×</button></td></tr>`}).join("")}
window.mastery=async(id,v)=>{let t=db.topics.find(x=>x.id===id);t.mastery=v;if(supabaseClient)await supabaseClient.from("topics").update({mastery:v}).eq("id",id).eq("user_id",user.id);else localStorage.setItem("jamv2",JSON.stringify(db));render()};
window.removeTopic=async id=>{if(!confirm("Delete this topic and linked records?"))return;db.topics=db.topics.filter(x=>x.id!==id);db.study=db.study.filter(x=>x.topic_id!==id);db.tests=db.tests.filter(x=>x.topic_id!==id);db.revisions=db.revisions.filter(x=>x.topic_id!==id);if(supabaseClient){await supabaseClient.from("topics").delete().eq("id",id);await supabaseClient.from("study_sessions").delete().eq("topic_id",id);await supabaseClient.from("tests").delete().eq("topic_id",id);await supabaseClient.from("revisions").delete().eq("topic_id",id)}else localStorage.setItem("jamv2",JSON.stringify(db));render()};
function opts(){return db.topics.map(t=>`<option value="${t.id}">${esc(t.subject)} — ${esc(t.name)}</option>`).join("")}
function modal(title,html,done){$("mt").textContent=title;$("form").innerHTML=html;$("modal").classList.add("show");$("form").onsubmit=async e=>{e.preventDefault();await done(new FormData($("form")));$("modal").classList.remove("show");render()}}
async function addRow(table,row){if(supabaseClient){row.user_id=user.id;let {data,error}=await supabaseClient.from(table).insert(row).select().single();if(error)alert(error.message);else return data}else{return row}}
$("addTopic").onclick=()=>modal("Add topic",`<div class="form-grid"><label>Subject<select name="subject">${subjects.map(s=>`<option>${s}</option>`).join("")}</select></label><label>Topic<input name="name" required></label><button class="primary">Add topic</button></div>`,async f=>{let row={id:crypto.randomUUID(),subject:f.get("subject"),name:f.get("name"),mastery:"Not started"};let x=await addRow("topics",row);db.topics.push(x||row);if(!supabaseClient)localStorage.setItem("jamv2",JSON.stringify(db))});
$("addStudy").onclick=()=>modal("Log study",`<div class="form-grid"><label>Date<input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Topic<select name="topic_id">${opts()}</select></label><label>Hours<input type="number" name="hours" min=".25" step=".25" required></label><label>Type<select name="type"><option>Theory</option><option>PYQ</option><option>Revision</option><option>Test</option></select></label><button class="primary">Save</button></div>`,async f=>{let row={id:crypto.randomUUID(),date:f.get("date"),topic_id:f.get("topic_id"),hours:+f.get("hours"),type:f.get("type")};let x=await addRow("study_sessions",row);db.study.push(x||row);if(!supabaseClient)localStorage.setItem("jamv2",JSON.stringify(db))});
$("addTest").onclick=()=>modal("Add topic test",`<div class="form-grid"><label>Date<input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Topic<select name="topic_id">${opts()}</select></label><label>Questions<input type="number" name="questions" min="1" required></label><label>Score<input type="number" name="score" min="0" required></label><button class="primary">Save</button></div>`,async f=>{let q=+f.get("questions"),s=+f.get("score"),tid=f.get("topic_id"),attempt=db.tests.filter(x=>x.topic_id===tid).length+1,row={id:crypto.randomUUID(),date:f.get("date"),topic_id:tid,questions:q,score:s,percent:q?s/q*100:0,attempt};let x=await addRow("tests",row);db.tests.push(x||row);if(!supabaseClient)localStorage.setItem("jamv2",JSON.stringify(db))});
$("addRevision").onclick=()=>modal("Record revision",`<div class="form-grid"><label>Topic<select name="topic_id">${opts()}</select></label><label>Date<input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Next revision<input type="date" name="next_date"></label><button class="primary">Save</button></div>`,async f=>{let row={id:crypto.randomUUID(),topic_id:f.get("topic_id"),date:f.get("date"),next_date:f.get("next_date")||null};let x=await addRow("revisions",row);db.revisions.push(x||row);if(!supabaseClient)localStorage.setItem("jamv2",JSON.stringify(db))});
function renderStudy(){let h=db.study.reduce((a,x)=>a+Number(x.hours||0),0);$("studyCards").innerHTML=`<div class="card"><div class="label">Total hours</div><div class="value">${h.toFixed(1)}</div></div><div class="card"><div class="label">Sessions</div><div class="value">${db.study.length}</div></div>`;$("studyRows").innerHTML=db.study.slice().reverse().map(x=>{let t=db.topics.find(t=>t.id===x.topic_id);return `<tr><td>${x.date}</td><td>${esc(t?.subject)}</td><td>${esc(t?.name)}</td><td>${x.hours}</td><td>${x.type}</td><td>—</td></tr>`}).join("")}
function renderTests(){let a=db.tests.length?db.tests.reduce((s,x)=>s+x.percent,0)/db.tests.length:0;$("testCards").innerHTML=`<div class="card"><div class="label">Attempts</div><div class="value">${db.tests.length}</div></div><div class="card"><div class="label">Average</div><div class="value">${pct(a)}</div></div>`;$("testRows").innerHTML=db.tests.slice().reverse().map(x=>{let t=db.topics.find(t=>t.id===x.topic_id);return `<tr><td>${x.date}</td><td>${esc(t?.subject)}</td><td>${esc(t?.name)}</td><td>${x.questions}</td><td>${x.score}</td><td>${pct(x.percent)}</td><td>${x.attempt}</td><td>—</td></tr>`}).join("")}
function renderRevs(){$("revRows").innerHTML=db.revisions.slice().reverse().map(x=>{let t=db.topics.find(t=>t.id===x.topic_id),n=db.revisions.filter(r=>r.topic_id===x.topic_id).length;return `<tr><td>${esc(t?.subject)}</td><td>${esc(t?.name)}</td><td>${n}</td><td>${x.date}</td><td>${x.next_date||"—"}</td><td>—</td></tr>`}).join("")}
function renderAnalytics(){let h=subjects.map(s=>[s,db.study.filter(x=>db.topics.find(t=>t.id===x.topic_id)?.subject===s).reduce((a,x)=>a+Number(x.hours||0),0)]),scores=subjects.map(s=>{let a=db.tests.filter(x=>db.topics.find(t=>t.id===x.topic_id)?.subject===s);return[s,a.length?a.reduce((q,x)=>q+x.percent,0)/a.length:0]});$("hoursChart").innerHTML=h.map(x=>`<div class="chartrow"><div class="chartlabel"><span>${x[0]}</span><b>${x[1].toFixed(1)}h</b></div><div class="mini"><i style="width:${Math.min(100,x[1]/Math.max(...h.map(y=>y[1]),1)*100)}%"></i></div></div>`).join("");$("scoreChart").innerHTML=scores.map(x=>`<div class="chartrow"><div class="chartlabel"><span>${x[0]}</span><b>${pct(x[1])}</b></div><div class="mini"><i style="width:${x[1]}%"></i></div></div>`).join("")}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(b.dataset.page).classList.add("active");$("title").textContent=b.textContent.replace(/^[^A-Za-z]+/,"")});
$("close").onclick=()=>$("modal").classList.remove("show");$("sf").onchange=renderTopics;$("mf").onchange=renderTopics;
$("emailForm").onsubmit=async e=>{e.preventDefault();if(!supabaseClient){$("authMsg").textContent="Add Supabase keys in config.js first.";return}let email=$("email").value,password=$("password").value;let r=await supabaseClient.auth.signInWithPassword({email,password});if(r.error){let c=await supabaseClient.auth.signUp({email,password});$("authMsg").textContent=c.error?c.error.message:"Account created. Check your email if confirmation is enabled."}};
$("googleBtn").onclick=()=>supabaseClient?supabaseClient.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+location.pathname}}):$("authMsg").textContent="Add Supabase keys in config.js first.";
$("signout").onclick=async()=>{if(supabaseClient)await supabaseClient.auth.signOut();location.reload()};$("sync").onclick=async()=>{if(supabaseClient){await loadCloud();render();alert("Synced.");}else alert("Local mode: add Supabase credentials for cloud sync.")};
authInit();
